--- 
:pingservers: 
- "http://rpc.weblogs.com/RPC2"
- "http://rpc.technorati.com/rpc/ping"
- "http://ping.feedburner.com"
- "http://r.hatena.ne.jp/rpc"
- "http://rpc.pingomatic.com/"
- "http://rpc.technorati.jp/rpc/ping"
- "http://blog.goo.ne.jp/XMLRPC"
- "http://api.my.yahoo.com/RPC2"
- "http://ping.bloggers.jp/rpc/"
#- "http://1470.net/api/ping"
- "http://rpc.blogrolling.com/pinger/"
- "http://blogsearch.google.com/ping/RPC2"
- "http://ping.ask.jp/xmlrpc.m"
- "http://ping.bloggers.jp/rpc/"
- "http://ping.namaan.net/rpc/"
- "http://rpc.reader.livedoor.com/ping"
- "http://ping.fc2.com"
- "http://www.bloglines.com/ping"
#- "http://bitacoras.net/ping/"
#- "http://blog.with2.net/ping.php/"
#- "http://blog-search.net/up.php"
#- "http://jugem.jp/?mode=NEWENTRY"
#- "ping.rss.drecom.jp"
- "http://ping.dendou.jp/"
- "http://rpc.icerocket.com:10080/"
#- "http://ranking.kuruten.jp/ping"
#- "http://www.accelanavi.com/anavi/ping.php"
- "http://ping.speenee.com/xmlrpc"
- "http://rpc.feedping.net/"
- "http://www.blogpeople.net/servlet/weblogUpdates"
:weblogname: "0:00の鐘はeternalic"
:weblogurl: "http://eternalic.blogspot.com"
:categoryname:
:rssurl: "http://eternalic.blogspot.com/feeds/posts/default"
